### ISSUE TITLE
Custom dataset？？？？

### ISSUE THREAD

**Issue by Z-zachary** [mlpc-ucsd/BDM#2]

**Comment by Z-zachary** [comment]
Thanks for your fantastic work.  

Can this work is applied on custom Work??

**Comment by TheKnight-Z** [comment]
Hi @Z-zachary ,

Could you please be more specific? What do you mean by "custom work" and "custom dataset"? 

I will close this issue. If you are interested in further discussion, open as your willingness.

Thank you.
