### ISSUE TITLE
Hello, how do I train pix3d datasets?

### ISSUE THREAD

**Issue by leezanla** [mlpc-ucsd/BDM#3]
Hello, thank you very much for your open source code, I read the paper, we can make the shape of pix3d into a point cloud. However, when I look at the code, it only trains the data sh files in shapnet, such as (example_train.sh), and does not train the files in pix3d, may I ask whether I should follow your form to another one? I am a new student, do not understand, looking forward to your reply! Thank you!

**Comment by TheKnight-Z** [comment]
@leezanla Thanks for your interest in our work! 

The file "example_train.sh" refers to the training of reconstruction model. If you want to change the training dataset, you should change the "dataset","dataset.root" etc. in the [file ](https://github.com/mlpc-ucsd/BDM/blob/main/experiments/example_train.sh)correspondingly and even rewrite a new dataloader if needed.
